language: java

jdk:
  - openjdk8
before_install:
  - chmod +x gradlew
  - chmod +x gradle/wrapper/gradle-wrapper.jar
script:
  - ./gradlew test build
after_success:
  - ./gradlew jacocoTestReport coveralls
before_deploy:
  - ./gradlew generateDescriptorJson
  - ./gradlew generatePom
deploy:
  - provider: releases
    skip_cleanup: true
    file: "build/libs/*"
    api_key: $GITHUB_API_KEY
    on:
      tags: true
      jdk: oraclejdk8
  - provider: bintray
    skip_cleanup: true
    file: "build/descriptor.json"
    user: $BINTRAY_API_USER
    key: $BINTRAY_API_KEY
    on:
      tags: true
      jdk: openjdk8