package moe.slk.clausewitz.hoi4.config

const val LAND_COMBAT_ORG_DICE_SIZE: Int = 4
const val LAND_COMBAT_STR_DICE_SIZE: Int = 2

const val LAND_COMBAT_ORG_ARMOR_ON_SOFT_DICE_SIZE: Int = 6
const val LAND_COMBAT_STR_ARMOR_ON_SOFT_DICE_SIZE: Int = 2

const val LAND_COMBAT_STR_DAMAGE_MODIFIER: Double = 0.05
const val LAND_COMBAT_ORG_DAMAGE_MODIFIER: Double = 0.05

const val LAND_COMBAT_STR_ARMOR_DEFLECTION_FACTOR: Double = 0.5
const val LAND_COMBAT_ORG_ARMOR_DEFLECTION_FACTOR: Double = 0.5
const val BASE_CHANCE_TO_AVOID_HIT: Int = 90
const val CHANCE_TO_AVOID_HIT_AT_NO_DEF: Int = 60