package moe.slk.clausewitz.hoi4.types

data class Battalion(
    var sprite: String = "",
    var map_icon_category: String = "",
    var priority: Double = 0.0,
    var ai_priority: Double = 0.0,
    var active: Boolean = false,
    var group: String = "",
    var type: List<String> = listOf(),
    var categories: List<String> = listOf(),
    var combat_width: Double = 0.0,
    var need: Map<String, Long> = mutableMapOf(),
    var manpower: Double = 0.0,
    var training_time: Double = 0.0,
    var can_be_parachuted: Boolean = false,
    var hardness: Double = 0.0,

    var maximum_speed: Double = 0.0,
    var max_strength: Double = 0.0,
    var max_organisation: Double = 0.0,
    var default_morale: Double = 0.0,
    var recon: Double = 0.0,
    var suppression: Double = 0.0,
    var weight: Double = 0.0,
    var supply_consumption: Double = 0.0,
    var reliability_factor: Double = 0.0,
    var casualty_trickleback: Double = 0.0,
    var experience_loss_factor: Double = 0.0,
    var equipment_capture_factor: Double = 0.0,
    var entrenchment: Double = 0.0,
    var soft_attack: Double = 0.0,
    var hard_attack: Double = 0.0,
    var air_attack: Double = 0.0,
    var defense: Double = 0.0,
    var breakthrough: Double = 0.0,
    var armor_value: Double = 0.0,
    var ap_attack: Double = 0.0,

    var essential: String = "",
    var transport: String = "",

    var forest: TerrainModifier = TerrainModifier(),
    var hills: TerrainModifier = TerrainModifier(),
    var mountain: TerrainModifier = TerrainModifier(),
    var plains: TerrainModifier = TerrainModifier(),
    var jungle: TerrainModifier = TerrainModifier(),
    var marsh: TerrainModifier = TerrainModifier(),
    var desert: TerrainModifier = TerrainModifier(),
    var fort: TerrainModifier = TerrainModifier(),
    var river: TerrainModifier = TerrainModifier(),
    var amphibious: TerrainModifier = TerrainModifier()

)

