package org.slk.clausewitz.hoi4.types

data class Division(
    var name: String,
    var division_names_group: String,
    var maximum_speed: Double = 0.0,
    var max_strength: Double = 0.0,
    var max_organisation: Double = 0.0,
    var default_morale: Double = 0.0,
    var recon: Double = 0.0,
    var suppression: Double = 0.0,
    var weight: Double = 0.0,
    var supply_consumption: Double = 0.0,
    var reliability_factor: Double = 0.0,
    var casualty_trickleback: Double = 0.0,
    var experience_loss_factor: Double = 0.0,
    var soft_attack: Double = 0.0,
    var hard_attack: Double = 0.0,
    var air_attack: Double = 0.0,
    var defense: Double = 0.0,
    var breakthrough: Double = 0.0,
    var armor_value: Double = 0.0,
    var ap_attack: Double = 0.0,
    var entrenchment: Double = 0.0,
    var equipment_capture_factor: Double = 0.0,
    var combat_width: Double = 0.0,
    var manpower: Double = 0.0,
    var training_time: Double = 0.0,
    var hardness: Double = 0.0,
    var need: MutableMap<String, Long> = mutableMapOf(),
    var priority: MutableMap<String, Double> = mutableMapOf(),
    var template: MutableMap<String, MutableMap<String, Int>> = mutableMapOf()
)